name: dataArk

services:
  dataarkapi:
    build:
      context: ..
      dockerfile: docker/Dockerfile
    ports:
      - "7845:7845"
    volumes:
      - ./archive:/archive
      - ./meili_dumps:/meili_dumps
    depends_on:
      database:
          condition: service_healthy
    command: [
      "-loc", "/archive/",
      "-mhost", "http://meili:7700",
      "-mkey", "masterkey",
      "-mdump", "/meili_dumps",
      "-dbhost", "database",
    ]

  meili:
    image: getmeili/meilisearch:v1.42
    environment:
      MEILI_MASTER_KEY: "masterkey"
      MEILI_DUMP_DIR: "/meili_dumps"
    volumes:
      - ./meili_data:/meili_data
      - ./meili_dumps:/meili_dumps

  database:
    image: postgres:17-alpine3.21
    volumes:
      - ./database:/var/lib/postgresql/data
    environment:
      POSTGRES_PASSWORD: "postgres"
      POSTGRES_DB: "echoark"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d echoark"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 30s

  singlefile-webservice:
    image: ghcr.io/h4rs0n/singlefile-webservice:latest
    container_name: singlefile-webservice
    ports:
      - "8080:8080"
    volumes:
      - ./archive:/usr/src/app/output
    restart: unless-stopped
    environment:
      - PORT=8080
      - TIMEOUT=60
      - OUTPUT_DIR=/usr/src/app/output
