package api

import (
	"github.com/gin-gonic/gin"
)

// routes.go 集中注册全部 /api 路由，便于检索 HTTP 表面。

func registerAPIRoutes(router *gin.Engine, authController *AuthController) {
	public := router.Group("/api")
	{
		public.POST("/login", authController.Login)
	}
	protected := router.Group("/api")
	protected.Use(AuthMiddleware())
	{
		protected.GET("/search", SearchByKeyword)
		protected.GET("/search/keywords", GetSearchKeywords)
		protected.POST("/uploadHtmlFile", AddHTMLFile)
		protected.POST("/upload", AddDocByHTMLFile)
		protected.POST("/archiveByURL", AddDocByURL)
		protected.GET("/archiveTask/:taskId", GetArchiveTaskStatus)
		protected.POST("/archive/clicks", RecordArchiveClick)
		protected.GET("/archive/rankings", GetArchiveRankings)
		protected.GET("/recommendations/archives", GetArchiveRecommendations)
		protected.GET("/archiveStats", GetArchiveStats)
		protected.POST("/archiveStats/refresh", RefreshArchiveStats)
		protected.GET("/archiveConsistency", GetArchiveConsistency)
		protected.POST("/archiveConsistency/repair", RepairArchiveConsistency)
		protected.DELETE("/archive", DeleteArchiveDocument)
		protected.GET("/discovery/sources", ListDiscoverySources)
		protected.POST("/discovery/sources", CreateDiscoverySource)
		protected.PUT("/discovery/sources/:id", UpdateDiscoverySource)
		protected.DELETE("/discovery/sources/:id", DeleteDiscoverySource)
		protected.POST("/discovery/sources/:id/fetch", FetchDiscoverySource)
		protected.GET("/discovery/sites/:id/graph", GetDiscoverySiteGraph)
		protected.GET("/discovery/sites/:id/backfill", GetDiscoveryBackfillCoverage)
		protected.PUT("/discovery/sites/:id/status", UpdateDiscoverySiteStatus)
		protected.POST("/discovery/sites/:id/backfill", RequestDiscoverySiteBackfill)
		protected.GET("/discovery/sites/:id/operations", GetDiscoverySiteOperations)
		protected.GET("/admin/discovery/crawl-queue", GetDiscoveryCrawlQueue)
		protected.POST("/admin/discovery/crawl-queue/run", RunDiscoveryCrawlQueue)
		protected.POST("/admin/discovery/article-assessments/backfill", BackfillArticleAssessments)
		protected.POST("/admin/discovery/article-assessments/rollback", RollbackArticleAssessments)
		protected.GET("/admin/assessment/metrics", GetAssessmentMetrics)
		protected.GET("/admin/assessment/queue", GetAssessmentQueue)
		protected.POST("/admin/assessment/queue/run", RunAssessmentQueue)
		protected.GET("/admin/discovery/domain-blacklist", ListDiscoveryDomainBlacklist)
		protected.POST("/admin/discovery/domain-blacklist", CreateDiscoveryDomainBlacklist)
		protected.DELETE("/admin/discovery/domain-blacklist/:id", DeleteDiscoveryDomainBlacklist)
		protected.POST("/discovery/candidates/:id/read", MarkDiscoveryCandidateRead)
		protected.POST("/discovery/candidates/:id/archive", ArchiveDiscoveryCandidate)
		protected.GET("/recommendations/today", GetRecommendationToday)
		protected.GET("/recommendations/today/summary", GetRecommendationTodaySummary)
		protected.GET("/recommendations/discovery-feed", GetDiscoveryRecommendationFeed)
		protected.POST("/recommendations/discovery-feed/refresh", RefreshDiscoveryRecommendationFeed)
		protected.GET("/recommendations/history", GetRecommendationHistory)
		protected.GET("/recommendations/days/:date/summary", GetRecommendationDaySummary)
		protected.GET("/recommendations/days/:date", GetRecommendationDay)
		protected.POST("/admin/recommendations/generate", GenerateRecommendationDay)
		protected.POST("/admin/recommendations/supplement", SupplementRecommendationDay)
		protected.GET("/recommendations/settings", GetRecommendationSettings)
		protected.GET("/recommendations/inventory", GetRecommendationInventory)
		protected.GET("/admin/recommendations/metrics", GetAdminProductMetrics)
		protected.PUT("/recommendations/settings", UpdateRecommendationSettings)
		protected.POST("/recommendations/items/:itemId/feedback", RecordRecommendationItemFeedback)
		protected.GET("/recommendations/items/:itemId/feedback", GetRecommendationItemFeedback)
		protected.GET("/recommendations/items/:itemId/context", GetRecommendationItemContext)
		protected.DELETE("/recommendations/items/:itemId/feedback", RevertRecommendationItemFeedback)
		protected.POST("/recommendations/preferences/reset", ResetRecommendationPreferences)
		protected.GET("/recommendations/blocks", ListRecommendationBlocks)
		protected.DELETE("/recommendations/blocks/:id", DeleteRecommendationBlock)
		protected.POST("/backup", CreateBackup)
		protected.POST("/backup/restore", RestoreBackup)
		protected.GET("/authChecker", authController.AuthChecker)
		protected.POST("/register", authController.Register)
	}
}
